### ISSUE TITLE
 permission denied, mkdir '/var/www/html/node_modules'

### ISSUE THREAD

**Issue by lupanvi** [balajidharma/basic-laravel-admin-panel#15]
Hi, I am trying to install your app but I can't, I get this error when running; ./vendor/bin/sail npm install

> npm ERR! code EACCES
> npm ERR! syscall mkdir
> npm ERR! path /var/www/html/node_modules
> npm ERR! errno -13
> npm ERR! Error: EACCES: permission denied, mkdir '/var/www/html/node_modules'
> npm ERR!  [Error: EACCES: permission denied, mkdir '/var/www/html/node_modules'] {
> npm ERR!   errno: -13,
> npm ERR!   code: 'EACCES',
> npm ERR!   syscall: 'mkdir',
> npm ERR!   path: '/var/www/html/node_modules'
> npm ERR! }
> npm ERR!
> npm ERR! The operation was rejected by your operating system.
> npm ERR! It is likely you do not have the permissions to access this file as the current user
> npm ERR!
> npm ERR! If you believe this might be a permissions issue, please double-check the
> npm ERR! permissions of the file and its containing directories, or try running
> npm ERR! the command again as root/Administrator.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/sail/.npm/_logs/2022-10-21T23_04_16_850Z-debug-0.log

I am running this app inside WSL in windows 10.
I am already running the console as admin.

what can I do? Thank you.

**Comment by balajidharma** [comment]
Hi, Issue related to server permission issue. Refer the https://laracasts.com/discuss/channels/general-discussion/laravel-sail-cannot-mkdir-permission-denied?page=1&replyId=684385
