### ISSUE TITLE
Show/Hide menus in navbar depending on the user roles

### ISSUE THREAD

**Issue by Fzoltan87** [balajidharma/basic-laravel-admin-panel#32]
It would be important for the menu item to disappear or appear based on permission.
How could this be solved?

Example:
All menu items: Dashboard, Permissions, Roles, Users
The Super Administrator role can see all menu items (Dashboard, Permissions, Roles, Users)
The Admin role must see the Dashboard and Users menu items
The Writer role must see the Dashboard menu item

**Comment by balajidharma** [comment]
Currently the admin panel not supporting this feature. I will add it to the backlog and implement the menu display based on permissions.

**Comment by Fzoltan87** [comment]
Thank you very much. I look forward to the update. Can I invite you for a coffee?

**Comment by juanjuan77** [comment]
hola buen dia,

me da el siguiente error:
"A `admin` menu not exists."

como podria resolverlo?

gracias!

**Comment by juanjuan77** [comment]
![image](https://github.com/balajidharma/basic-laravel-admin-panel/assets/15437504/c1479f73-3216-4562-803c-4847377b8d9e)

**Comment by balajidharma** [comment]
@juanjuan77 make sure to run the migration with the seeder.

./vendor/bin/sail artisan vendor:publish --provider="BalajiDharma\LaravelMenu\MenuServiceProvider"
./vendor/bin/sail artisan migrate --seed --seeder=AdminCoreSeeder


Please create a new issue if you still have the issue.

**Comment by balajidharma** [comment]
Added roles for menu item. Also, displayed menu based on roles

![image](https://github.com/balajidharma/basic-laravel-admin-panel/assets/6037466/aa0c5375-8a50-48a3-81d0-378c1956c113)

**Comment by jeddiesaudi** [comment]
My sidebar menu doesn't appear


![Image](https://github.com/balajidharma/basic-laravel-admin-panel/assets/54430706/f7daed2b-be22-460f-9659-2368a4b4f524)

**Comment by balajidharma** [comment]
Go to admin panel on http://localhost/admin
