### ISSUE TITLE
Alpine.js

### ISSUE THREAD

**Issue by NickWalker-hub** [balajidharma/basic-laravel-admin-panel#50]
It's Alpine.js, right ? Why is it not added to the default project ? I was getting errors while running, and after 30 minutes I managed to figure out what was wrong.  
 So how do I add Alpine.js ? 
  
![Alpine-js](https://github.com/balajidharma/basic-laravel-admin-panel/assets/113579012/f1937055-6398-448c-a4d9-ffb2068aeda5)

**Comment by balajidharma** [comment]
@NickWalker-hub package.json has alpinejs 

https://github.com/balajidharma/basic-laravel-admin-panel/blob/1.x/package.json
