### ISSUE TITLE
Error when open admin/user when login as other role except super-admin

### ISSUE THREAD

**Issue by kepinaza** [balajidharma/basic-laravel-admin-panel#68]
I have an issue, when i login as Example User in this case has writer role, and writer role has permission to list user. when i click the Users menu it showed this error:

`Too few arguments to function BalajiDharma\LaravelAdminCore\Policies\PermissionPolicy::adminUpdate(), 1 passed in F:\sman2web\vendor\laravel\framework\src\Illuminate\Auth\Access\Gate.php on line 811 and exactly 2 expected`

this also happen with other role except super-admin role, although make another role with all permission is not solved the issue.

this issue has no impact on super-admin role as i known this permission managed by `Gate:before` rule at AuthServiceProvider.

sorry, my english is bad, but maybe you can help me with this issues

**Comment by balajidharma** [comment]
@kepinaza try with the latest released version

**Comment by rajucs** [comment]
Still getting this problem where i am using latest version 2.x

**Comment by balajidharma** [comment]
@rajucs do the composer update and verify it.

**Comment by rajucs** [comment]
Thank you so much worked fine.
